import "../styles/globals.css"

import type { Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"
import { NavbarProvider } from "./_components/NavbarContext"
import Footer from "./_components/Footer"
import Header from "./_components/Header"
import Gtag from "@/lib/gtag"

export const metadata: Metadata = {
  title: "Hugo Coding",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Gtag />
      <body className="bg-black">
        <ClerkProvider>
          <NavbarProvider>
            <Header />
            <div className="bg-white pt-[120px] ease-in">{children}</div>
            <Footer />
          </NavbarProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
