import "../styles/globals.css"

import { SpeedInsights } from "@vercel/speed-insights/next"
import type { Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"

import Gtag from "@/lib/gtag"
import { NavbarProvider } from "@/components/landing/NavbarContext"
import Header from "@/components/landing/Header"
import Footer from "@/components/landing/Footer"

export const metadata: Metadata = {
  title: "Hugo Coding",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Gtag />
      <SpeedInsights />
      <body className="bg-black">
        <ClerkProvider>
          <NavbarProvider>
            <Header />
            <div className="bg-white pt-[120px] ease-in">{children}</div>
            <Footer />
          </NavbarProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
